extraction:
  cpp:
    after_prepare: 
      - python report.py 50
  cobol:
    after_prepare: 
      - python report.py 50
  csharp:
    after_prepare: 
      - python report.py 50
  java:
    after_prepare: 
      - python report.py 50
  javascript:
    after_prepare: 
      - python report.py 50
  python:
    after_prepare: 
      - python report.py 50
